
name: CI/CD for Flask App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run Tests (if any)
      - name: Run Tests
        run: |
          python -m unittest discover -s tests

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Checkout code again for deployment
      - name: Checkout Code
        uses: actions/checkout@v3

      # Deploy using SSH (example)
      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER: ${{ secrets.SERVER }}
          USER: ${{ secrets.USER }}
        run: |
          ssh -i ~/.ssh/id_rsa $USER@$SERVER 'cd /path/to/project && git pull && systemctl restart flask-app'
