name: CI/CD Workflow for Help Desk System

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Python for optional testing
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Step 3: Install dependencies (for testing or linting)
      - name: Install Dependencies
        working-directory: help-desk-system
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run tests (if applicable)
      - name: Run Tests
        working-directory: help-desk-system
        run: python -m unittest discover -s tests || echo "No tests found"

      # Step 5: Build the Docker image
      - name: Build Docker Image
        working-directory: help-desk-system
        run: docker build . --file Dockerfile --tag help-desk-system:$(date +%s)

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Deploy to the server
      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER: ${{ secrets.SERVER }}
          USER: ${{ secrets.USER }}
        run: |
          ssh -i ~/.ssh/id_rsa $USER@$SERVER << 'EOF'
          cd /path/to/deployment/directory
          docker stop help-desk-system || true
          docker rm help-desk-system || true
          docker pull help-desk-system:latest
          docker run -d --name help-desk-system -p 5000:5000 help-desk-system
          EOF
