name: Docker Image CI/CD for Flask Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up Python environment (optional if running pre-build tests)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Install dependencies (if testing or linting is needed)
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run tests (if any are available)
      - name: Run Tests
        run: python -m unittest discover -s tests

      # Build the Docker image
      - name: Build the Docker Image
        run: docker build . --file Dockerfile --tag flask-app:$(date +%s)

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Deploy using SSH
      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER: ${{ secrets.SERVER }}
          USER: ${{ secrets.USER }}
        run: |
          ssh -i ~/.ssh/id_rsa $USER@$SERVER << 'EOF'
          cd /path/to/your/project
          docker stop flask-app || true
          docker rm flask-app || true
          docker pull flask-app:latest
          docker run -d --name flask-app -p 5000:5000 flask-app
          EOF
